### ISSUE TITLE
Line Breaks not working in UI mode

### ISSUE THREAD

**Issue by lordratner** [natekspencer/hacs-vestaboard#16]
Hello again

In the Vestaboard APIs you can use \n as a line break. This is broken in the Home Assistant integration when using the UI. I tried passing it through the message option, no dice. It does work using the VBML option, however, but that's most likely because you must use YAML mode for the VBML option 

I'm getting the same problem with my script, even though the script uses VBML. I suspect it has something to do with the UI stripping out dangerous characters, but is there any way to override this behavior? This isn't a problem with the integration specifically, but I figured I'd ask before going to the HA forums.

Seriously though, this integration is *great.* The SVG option is really neat.

**Comment by natekspencer** [comment]
Thanks, if you add `multiline: true` under your text selector, it will update the UI to better allow for multiline entry. I'll add this to the service as well:

```yaml
    message:
      name: Message
      description: The message to send.
      required: false
      selector:
        text:
          multiline: true
```
