### ISSUE TITLE
How to send next line ?

### ISSUE THREAD

**Issue by offlinesurfer** [natekspencer/hacs-vestaboard#4]
I want to create a automation which shows todays weather.
Is there a way to send a next line command (\n is not working) ?

**Comment by natekspencer** [comment]
"\n" should work, for example:

```yaml
service: vestaboard.message
data:
  device_id:
    - 9279f3b67d44b4c1f971a6b3a41075c3
  message: "This\nis\nmy\nmessage"
```

**Comment by natekspencer** [comment]
Additionally, you can do it these two ways:

```yaml
service: vestaboard.message
data:
  device_id:
    - 9279f3b67d44b4c1f971a6b3a41075c3
  message: >-
    Another
    
    Multiline
    
    Message
```
```yaml
service: vestaboard.message
data:
  device_id:
    - 9279f3b67d44b4c1f971a6b3a41075c3
  message: |-
    Alternative
    Multiline
    Message
```
